name: Shreesh Agency
favicon: null
layout_spectrum: 0.75209
typography_spectrum: 0.6470357934013009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.478926217649132
  lightness: 0.34584206668660045
  saturation: 0.6761548491194844
  rhythmicContrast: 0.33897628425620496
purpose: []
