name: Shreesh Agency
favicon: null
layout_spectrum: 0.75209
typography_spectrum: 0.6470357934013009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#8fa4bf'
    - '#e8e8e8'
    - '#9b3006'
    - '#1d673a'
  brandStrength: 0.5
  lightness: 0.34584206668660045
  saturation: 0.6761548491194844
  rhythmicContrast: 0.33897628425620496
purpose: []
